sudo: require
dist: xenial
language: bash
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y emacs
script:
- make
- bash push.sh
branches:
  only:
  - master
dd:
  secure: K/tWrIf3XuyFUAZ4FWVBMYcX9gcHw3/BITfyrqm06K4xurXaMRmN+Zym/vh6QbQluQK8h3lztFhRMnn7uieiczRqmi8gsVC5ylrsyxJC0luYeYk3R/vhv/SUK1uf/jBMLY3GxGGkJpmZRHZ2ObfgI+oRXjQuG42UmsdNOMcrAKO04qx0woVIs6yAR4pfDR6dIVSYxN1QzX3mfUGFFuCiqHYWV2bPmMu4sGxu7dKMDzgd7S6gAfvD7uQb3yyYyJXLVvaPzPkgpmphvcLHeGji8px4pNfBVcsNpETjXrrXRAI1yy1afuVvX26Zq+i0Lh/G9e8y8LxpFmmpEn4a13qctmTrPBU0Swiwl+Puczje36ciH869UJ3CqD71HtbOvqLJHZTMSt5zzC2DnF8CtcYrP+VMIxrbTdhfiZnOcIZwXzJi+2IYdc4Pkkeu+JS4fV3cpL/P2rqW6V/ofnome94b0eidF1ZCos/Ed3EJWFqygSgl1bIeaoFzPdDyNSdfHPHriKwSNAQvdOKey2PZlxH0sHp3oYy/v3buhKNBSI7qE/zYz9uQPIwX9g+nvlCkkO5xgeDb+xkuRaHPMYXexUjCKjM7AB5bGtE6wYVeZRVuS2B7GhqTBmkEIjGllXX+qKktlgOb62aE7OLidG4+ilIsnlYpruCP4vc3HQI82DPItIQ=
