name: Create html page after push
on:
  push:
    branches:
      - master
jobs:
  htmlize:
    name: Create index.html and commit
    runs-on: ubuntu-latest
    steps:
    - name: Prepare
      run: sudo apt install emacs
    - name: Installing packages
      run: emacs --batch --exec "(progn (package-initialize) (add-to-list 'package-archives '(\"melpa\" . \"https://melpa.org/packages/\")) (setq package-check-signature nil) (package-refresh-contents) (package-install 'htmlize))"
    - name: Clone
      run: git clone https://github.com/konstantin-morenko/web-page-template.git
    - name: Htmlize
      run: cd web-page-template; make
    - name: Commit
      run: |
        cd web-page-template
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Add changes" -a
    - name: Push changes
      uses: konstantin-morenko/web-page-template
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
